apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.releaseName }}-secret
  labels:
    app: transferencias
    service: {{ .Values.releaseName }}
data:
  ConnectionStrings__Oracle: {{ .Values.config.oracle }}
  ConnectionStrings__Active: {{ .Values.config.active }}
  ApiKeyConfiguration__Key: {{ .Values.config.apikey.value }}
---